version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "80:5000"
    command: sh -c "FLASK_DEBUG=1 FLASK_APP=src/quickstart/app/sign-in.py pipenv run flask run -h 0.0.0.0"
